### ISSUE TITLE
Set up Grunt (linters/minification/copyright)

### ISSUE THREAD

**Issue by yashpatel5400** [yashpatel5400/intertect#8]
Grunt is really good for automating garbage no one wants to worry about but that has to be done (i.e. "minification, compilation, unit testing, linting" according to https://gruntjs.com/). Setting this up now will help tremendously save time for local testing later on.

Choose a linter for both JS and HTML (remember, we'll be sticking with this for all of development, so make sure it's something that's well maintained/used). I know there's something called ESLint, which is widely used for JS linting, not sure about HTML. 

This may also cover #7, if we're able to automate copyright placement with Grunt (which seems like a totally reasonable thing to expect). I'll paste the exact copyright text below once I've got it written
**JS:**
```
/**
* Copyright (c) 2018-present, Yash Patel and Peter DeLong
* All rights reserved.
*/
```

**HTML:**
```
© 2018-present Yash Patel and Peter DeLong. All rights reserved.
```

**Comment by pdelong** [comment]
JavaScript auto-copyright is done but it will be difficult for the HTML. I suggest we do that as part of templating
